name: runfossa

on: push

jobs:
  runfossa:
    name: fossa cli code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run foss cli
        uses: fossas/fossa-cli
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
